# Generated by Django 2.2.1 on 2019-05-19 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20190518_1253'),
        ('accounts', '0009_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='من فضلك ادخل رقم موبايل صحيح', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must match egyptian format', regex='^01[1|0|2|5][0-9]{8}$')])),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_status', models.PositiveIntegerField(default=1)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.City')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000)])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.Product')),
            ],
        ),
    ]
