# Generated by Django 2.2.1 on 2019-05-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='order',
        ),
        migrations.AddField(
            model_name='orderimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem'),
            preserve_default=False,
        ),
    ]
