# Generated by Django 2.2.1 on 2019-05-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190522_0502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderImage',
        ),
    ]
