# Generated by Django 2.2.1 on 2019-05-22 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
