# Generated by Django 2.2.1 on 2019-05-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('r', 'تم رفض اللسعر'), ('a', 'تم قبول السعر')], default='w', max_length=5),
        ),
    ]
