# Generated by Django 2.2.1 on 2019-05-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190527_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='img',
            field=models.ImageField(blank=True, upload_to='orders/%Y/%m/%d'),
        ),
    ]
