# Generated by Django 2.2.1 on 2019-05-28 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190527_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0,validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default=('a','في الانتظار') ,choices=[('r', 'تم رفض اللسعر'), ('a', 'تم قبول السعر')], max_length=5),
        ),
    ]
